### ISSUE TITLE
Update WiFi blacklist

### ISSUE THREAD

**Issue by Helium314** [n76/DejaVu#32]
Could you add "CDWiFi",  "Regiojet - zluty"/"RegioJet - zluty" (Czech transport companies), "WESTlan" (Austrian Westbahn) and "Wifi in de trein" (Dutch NS) to the wifi blacklist?

And maybe the "OEBB" entry could be changed to only blacklist "OEBB" and not the stationary "OEBB-station" networks.

**Comment by n76** [comment]
Fixed in 48baa14b3fab99c7af3344492bbd14fecff389eb

**Comment by Lee-Carre** [comment]
@n76

Aside from #41, you may also wish to peruse the [SSID blacklist of RadioCells](/openbmap/radiocells-scanner-android/blob/master/android/app/src/main/java/org/openbmap/services/wireless/blacklists/SsidBlackListBootstraper.java).

I noticed, in my searching, that they used to do **B**SSID blacklisting client-side, but moved it to server-side.
