### ISSUE TITLE
There is no donation link

### ISSUE THREAD

**Issue by tekhedd** [n76/DejaVu#4]
I have no financial way to thank the project. Clearly, the absence of a paypal tip jar is a bug in the project documentation! (I have too many ongoing projects to contribute with code so I figured, you know, cash is always welcome.)

I found DejaVu in the F-Droid store and wanted to use it so badly that I switched roms and stopped using gapps. :) The least I can do is buy a beer.

**Comment by n76** [comment]
I've considered my paltry few open source projects and contributions to other projects to be my pay back into the ecosystem. It allows me feel less guilty about using all the fine software and apps that others put their time and effort into.

It looks like you've already contributed to a number of projects, consider that payment for my time on this project.
