### ISSUE TITLE
How to open database

### ISSUE THREAD

**Issue by mu88** [n76/DejaVu#49]
Hi 👋🏻

I'd like to take a look into the database to see which data I've already collected.

Where is the DB located on my device and how can I open it? Maybe it's even worth adding these information to `README.md`?

Best regards and thanks

**Comment by Helium314** [comment]
It's located in `/data/data/org.fitchfamily.android.dejavu/databases`, so you need root privileges to access it.

**Comment by mu88** [comment]
Thx! And what kind of DB is it? SQLite?

**Comment by Helium314** [comment]
Yes, SQLite
