### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by ale5000-git** [n76/DejaVu#6]
The latest build failed, look [here](https://f-droid.org/wiki/page/org.fitchfamily.android.dejavu).

**Comment by n76** [comment]
On that page the claimed link to the log for the failed build is https://f-droid.org/wiki/index.php?title=org.fitchfamily.android.dejavu/lastbuild_6&action=edit&redlink=1

When I follow that I get a message to the effect that the wiki page for it doesn't exist. On that there is a link for searching for log files: https://f-droid.org/wiki/index.php?title=Special%3ALog&type=&user=&page=org.fitchfamily.android.dejavu%2Flastbuild+6&year=&month=-1&hide_tag_log=1

Using that search page for a log file for DejaVu turns up nothing.

If you can help me find the actual log showing the failure I will have a better chance on correcting whatever it is that F-Droid's build system is having a problem with.

**Comment by ale5000-git** [comment]
I have reported it [here](https://gitlab.com/fdroid/fdroiddata/issues/1060).

**Comment by ale5000-git** [comment]
@n76: In the meantime that they fix the issue can you please release a new version with the startup crash fix?
So once the issue is fixed I already get the latest version.

**Comment by ale5000-git** [comment]
The latest build was published.
